name: CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Run Prettier
      - name: Run Prettier
        run: npm run format

      # Run ESLint
      - name: Run ESLint
        run: npm run lint

      # Run Tests
      - name: Run Tests
        run: npm test
        
