name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Prettier
      - name: Run Prettier
        run: npm run format

      # Run ESLint
      - name: Run ESLint
        run: npm run lint

      # Run Tests
      - name: Run Tests
        run: npm test

      # Build the application
      - name: Build Application
        run: npm run build
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
